### ISSUE TITLE
FTP error response 421

### ISSUE THREAD

**Issue by gadnis** [DPDBaltics/PrestaShop-1.7#47]
Hi,

I get error after pressing button "Išsaugoti ir atsisiųsti etiketę" in order page.

Error message:
**File has been created but could not be sent to FTP Server. Error Explanation: FTP response 421 received. Server closed connection.**

Is this a module problem?

_PrestaShop Version 1.7.6.8
PHP Version 7.2.34
„MySQL“ versija 10.3.35-MariaDB-log
DPD modulio versija 3.2.13_

**Comment by DPDBaltics** [comment]
Sveiki,

Problemos mūsų pusėje, sprendžiama aukščiausi prioritetu.


From: Edvinas Gurevicius ***@***.***>
Sent: 2023 m. kovo 3 d., penktadienis 13:29
To: DPDBaltics/PrestaShop-1.7 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DPDBaltics/PrestaShop-1.7] FTP error response 421 (Issue #47)


Hi,

I get error after pressing button "Išsaugoti ir atsisiųsti etiketę" in order page.

Error message:
File has been created but could not be sent to FTP Server. Error Explanation: FTP response 421 received. Server closed connection.

Is this a module problem?

PrestaShop Version 1.7.6.8
PHP Version 7.2.34
„MySQL“ versija 10.3.35-MariaDB-log
DPD modulio versija 3.2.13

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDPDBaltics%2FPrestaShop-1.7%2Fissues%2F47&data=05%7C01%7Cairidas.dauda%40dpd.lt%7C853b623858bb409a8e5808db1bda8c99%7C1de9dafc9e1a4b0e8db23abcb1b97fd9%7C0%7C0%7C638134397695425457%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=npK%2Bhe8LcR2F4SMS%2FtHzZVErapIH8oVcWAlOGYONEo8%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASNQC2DJVVOR2MKMTXNPNY3W2HIZNANCNFSM6AAAAAAVOP3RIQ&data=05%7C01%7Cairidas.dauda%40dpd.lt%7C853b623858bb409a8e5808db1bda8c99%7C1de9dafc9e1a4b0e8db23abcb1b97fd9%7C0%7C0%7C638134397695425457%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PLZsMHuBoLDV9NADzH9WdRFCKX0o4ImdJAxp2xcLEHE%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Šis elektroninis laiškas ir bet kokie su juo perduodami dokumentai yra skirti tik nurodytiems gavėjams. Laiške ar jo prieduose esanti informacija gali būti konfidenciali ir jos panaudojimas ar atskleidimas yra ribojamas. Jeigu gavote šį laišką per klaidą, informuojame, kad laiško ar jo priedų atskleidimas kitiems asmenims, kopijavimas ar kitoks platinimas yra griežtai draudžiamas ir gali būti neteisėtas. Prašome nedelsiant ištrinti šį laišką ir visus jo priedus, neišsaugojant kopijų. Taip pat primename, kad gavėjas turėtų patikrinti laišką ir bet kuriuos priedus prieš juos atidarydamas, nes siuntėjas neatsako už žalą, kurią galimai padarytų su šiuo laišku atkeliavęs virusas.

This e-mail and any files transmitted with it are intended for the use of the individual or entity, to which they are addressed, only. It may contain confidential or legally restricted information. If you were not the intended recipient of this message, you are hereby notified that unauthorized disclosure, copying or distribution of this information is strictly prohibited and may be illegal. Please immediately delete this e-mail with all files from your system without retaining copies. Finally, the recipient should check this e-mail and any attachments for the presence of viruses. The sender accepts no liability for any damage caused by any virus transmitted by this e-mail.

**Comment by justelis22** [comment]
Hi there @gadnis,

Could you please send us access to your back office and FTP credentials to support@invertus.eu?

We will investigate the case, as at the moment, we were not able to replicate the same error locally.

Best Regards,
Invertus Support team.

**Comment by gadnis** [comment]
Hi, @justelis22, email sent.
