### ISSUE TITLE
bad price rules logic

### ISSUE THREAD

**Issue by gadnis** [DPDBaltics/PrestaShop-1.7#52]
There is some serious issues with having large amount of DPD zones and price rules.

In our web store we have 840 price rules because of limitation of how merchant can set price rule and 38 zones. 
This makes a lot of mysql database stress on page load.

To reproduce:

1. Create many (or at least few) dpd price rules 
2. Set _PS_DEBUG_PROFILING_ to true
3. Open your page
4. Add some product in the card and refresh
5. Look for Table stress heading
6. Look for Object model instances

Our profiling information:
[Table stress picture](https://prnt.sc/qMhkJT51d0zS)
[Object model instances](https://prnt.sc/NNeO6psh9ObG)

Problem / Suggestions
1. why this code is being run in every page in first place? It should run only when choosing carrier in order confirmation page
2. There should be some different logic for price rules creation. For example 
a. it should have ability to set carrier price as percentage from cart total. Something like native prestahop price rules (see [pic.](https://prnt.sc/H-NCx-OaoZ7R))

**Comment by justelis22** [comment]
Hey there @gadnis,

The information was forwarded to our development team, as soon as we have some updates, we will let you know!

--
Best Regards,
Invertus Supporrt team.

**Comment by Laimonas-Mituzas** [comment]
Also encountered issues with Price rules on Multistore.
The first Price rule is taken to action in certain shop by rule configuration. Meanwhile in other shops showing "Free delivery"
I have provided info for support team by email a month ago. I can repeat it hear if necessary.

**Comment by justelis22** [comment]
Hello there @gadnis,

We have optimized the price rule queries, the upcoming release, which should be done next week will have the fix included.

As for the @Laimonas-Mituzas, the DPD Baltics module is not fully compatible with PrestaShop Multistore functionality, however, we recently analyzed the behavior of the price rules and it should not be the case.

Could you please send me more information via email - support@invertus.eu regarding this case?
Please attach all of the necessary details to replicate your environment so that we would be able to recreate the issue from our side.

Best Regards,
Invertus Supporrt team.

**Comment by justelis22** [comment]
Closing the issue, both topics should be resolved in the last couple of releases.

If anything, don't hesitate to reach out!

Best Regards,
Invertus Support team.

**Comment by gadnis** [comment]
Hi @justelis22  @MarijusDilys 

Could you let me know if there will be an option to set dynamic pricing in the near future, as suggested in this issue description (see above) and in this [picture](https://prnt.sc/H-NCx-OaoZ7R)?

**Comment by MarijusDilys** [comment]
Hi @gadnis,

For now, there is no priority for this feature request. We're focused on PrestaShop 9 compatibility and fixing known issues.

If you can, create a new GitHub issue as a feature request to separate it from this ticket. Thanks!

--
Best regards,
Marijus
